### ISSUE TITLE
ResultsPerPage component doesn't accept `defaultValue` prop anymore

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-search-ui#101]
Package version (if known): [react-searchkit@v1.0.0-alpha.5](https://github.com/inveniosoftware/react-searchkit/tree/v1.0.0-alpha.5)

## Describe the bug
RSK refactored the way the `ResultsPerPage` component initializes the state, so the `defaultValue` prop was removed.

## Expected behavior
Remove the unnecessary property from [here](https://github.com/inveniosoftware/invenio-search-ui/blob/master/invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/Results.js#L43)

**Comment by ppanero** [comment]
Closed by #111
