### ISSUE TITLE
styles: top search should use icon instead of text

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-search-ui#109]
## Describe the bug

The top search bar on the search bar is using a button with the text "Search" instead of a magnifier glass.

Currently looks like this:

![Screenshot 2020-11-30 at 00 24 16](https://user-images.githubusercontent.com/1698163/100556437-bc4a2a80-32a2-11eb-9023-46e934e3e64a.png)

It should look like this:

<img width="1699" alt="upload_3f97b7bc6c504287fbedde23577ea6db" src="https://user-images.githubusercontent.com/1698163/100556444-cbc97380-32a2-11eb-9aa2-ca773b40f48b.png">

**Comment by ppanero** [comment]
Result when using the two linked PRs (cookiecutter and invenio-search-ui)

![Screenshot 2020-12-01 at 13 21 16](https://user-images.githubusercontent.com/6756943/100740125-7becc880-33d8-11eb-803a-ad6606c7b998.png)
