### ISSUE TITLE
react: i18next not implemented in repository

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-search-ui#130]
Package version (if known): v8

## Describe the bug

if the latest search-ui is used other than app-rdm - this will through an error: https://github.com/inveniosoftware/invenio-search-ui/pull/127/files -  dont think we have implemented the i18next for this repo? right?

**Comment by mb-wali** [comment]
## Proposed Solution
* add the i18next workflow for this repo
* mark/extract and push the files to the transifex
* replace the mentioned above link import with corresponding repo import.
