### ISSUE TITLE
Multi use searchbar: allow empty search

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/invenio-search-ui#152]
Multi use searchbar should allow an empty search to be triggered.
The empty search should be done in the default selected option of the dropdown.
To be able to choose where an user wants to trigger an empty search, the dropdown should be displayed when clicking in the searchbar.
Also the search icon/button should work, meaning that if it's clicked, a search should be triggered.

**Comment by dfdan** [comment]
After a discussion with @jrcastro2 on discord, I've had a little think and we've also discussed internally. 

I understand that where the mutli-use search bar provides >1 context to search in, clicking the magnifier / hitting enter would be amiguous. However if there's only 1 context defined I can't see a reason why a blank search (ie hitting enter or clicking the mangnifier when there's no input) could reasonably behave as it has historically. 

Where multiple contexts are available, it might be appropriate to allow the default to be configured? This is less of an issue for us at present. 

CC'ing @chriz-uniba and @fenekku who have also mentioned noticing this issue / may have opinions.

**Comment by fenekku** [comment]
The way it's described with a default option for the empty search sounds good to us. We will give more feedback when released.
