### ISSUE TITLE
Location of angular templates

### ISSUE THREAD

**Issue by blixhavn** [inveniosoftware/invenio-search-ui#8]
What's the reasoning for keeping the angular templates in NPM? E.g.
```
<invenio-search-facets
template="{{ url_for('static', filename='node_modules/invenio-search-js/dist/templates/facets.html') }}">
</invenio-search-facets>
```

Is it as a kind of "separation of concerns"? Won't this make it really hard to customize the templates?

Could a solution be to at least have these paths defined in the config and thus being overridable?

**Comment by jirikuncar** [comment]
@blixhavn there are only some default templates in NPM package so it can be tested and it works with default values. You can add your own templates in e.g. `invenio_theme/static/js/tind-theme/search/facets.html` (don't forget to run `(inveniomanage|tind) collect`).

**Comment by blixhavn** [comment]
Yeah, I can add my own templates, but how would I get the search UI to load/use them? I mean, since their path is hardcoded in this template, is there any way I can overload that?

**Comment by jirikuncar** [comment]
You can create a custom config variable in your template.
