### ISSUE TITLE
Implement re-usable search app

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-search-ui#82]
Right now, `invenio-search-ui` provides a view and a template for the default `/search` page. With this implementation, it is easy to customize the existing page: you can extend the Jinja template and override blocks.

If you (or the user in his instance) need to create new pages with search apps that are quite different from the existing, this solution is not very flexible: the limitation is that when extending from the default `search.html`, the default extends from `config.SEARCH_UI_BASE_TEMPLATE`. If you change that config variable to `mysearch_base.html`, then all search pages, even the default one, will extend from the new template `mysearch_base.html`.

A solution would be to change the default search blueprint in this module and create a re-usable view, where the Jinja template can be injected as view variable and not a global unique config variable.

**Comment by ntarocco** [comment]
Should be fixed with RSK. @slint can you confirm? Can we close?

**Comment by slint** [comment]
Yup, in combination with the RSK search config helpers, this is pretty easy now, i.e. you extend the base `search.html` and then generate RSK config. I guess a task could be to document an example of that?
