### ISSUE TITLE
global: define SearchApp internal configuration

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-search-ui#86]
The default provided SearchApp component, accepts a `config` property, which is then used internally to initialize things like:

- the `axios` client for making the search requests (URL, parameters, HTTP headers, etc)
- facets, sorting, and pagination options
- list/grid view layouts
- component templates overriding

The schema/format of this configuration should be strictly defined so that:

- users of the component know how to use it
- Python utilities can be written to produce this config (e.g. from an Invenio-Records-REST endpoint)

**Comment by Glignos** [comment]
https://gist.github.com/Glignos/ed80aff76798436fc0915496a05bead0
